# Generated by Django 6.0 on 2026-01-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuebook",
            name="returned",
            field=models.BooleanField(default=False),
        ),
    ]
